name: Path To Live Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  actions: read
  checks: write
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

defaults:
  run:
    shell: bash
    working-directory: terraform/account

env:
  TFLINT_VERSION: 0.50.1

jobs:
  lint-and-validate:
    name: 'Validate Infrastructure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Parse terraform version
        id: tf_version_setup
        run: |
          if [ -f ./versions.tf ]; then
            terraform_version=$(cat ./versions.tf | sed -r -n 's/.*required_version.*"(.*)"$/\1/p' <&0)
            echo "- Terraform version: [${terraform_version}]" >> $GITHUB_STEP_SUMMARY
            echo "TERRAFORM_VERSION=${terraform_version}" >> $GITHUB_OUTPUT
          fi

      - name: "Terraform version [${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}]"
        run: echo "terraform version [${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}]"

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - uses: terraform-linters/setup-tflint@ae78205cfffec9e8d93fd2b3115c7e9d3166d4b6 # v5
        name: Setup TFLint
        with:
          tflint_version: v${{ env.TFLINT_VERSION }}

      - name: Configure OIDC AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: arn:aws:iam::631181914621:role/oidc-opg-shared-network-firewall-production
          role-session-name: opg-shared-network-firewall-github-actions-oidc-main-build
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Format Check Terraform
        id: tf_fmt
        run: terraform fmt -check -recursive

      - name: Validate Terraform
        id: tf_validate
        run: |
          terraform init
          terraform validate

      - name: Lint Terraform
        id: tf_lint
        run: tflint --recursive

  plan-and-apply:
    name: Plan & Apply ${{ matrix.environment }}
    needs: [lint-and-validate]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: "Development"
            workspace_environment: "development"
            role: "oidc-opg-shared-network-firewall-shared-development"

          - environment: "Production"
            workspace_environment: "production"
            role: "oidc-opg-shared-network-firewall-shared-production-main"

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Parse terraform version
        id: tf_version_setup
        run: |
          if [ -f ./versions.tf ]; then
            terraform_version=$(cat ./versions.tf | sed -r -n 's/.*required_version.*"(.*)"$/\1/p' <&0)
            echo "- Terraform version: [${terraform_version}]" >> $GITHUB_STEP_SUMMARY
            echo "TERRAFORM_VERSION=${terraform_version}" >> $GITHUB_OUTPUT
          fi

      - name: "Terraform version [${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}]"
        run: echo "terraform version [${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}]"

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}
          terraform_wrapper: false


      - name: Configure OIDC AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: arn:aws:iam::631181914621:role/oidc-opg-shared-network-firewall-${{matrix.workspace_environment}}
          role-session-name: opg-shared-network-firewall-github-actions-oidc-main-build
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Setup
        run: |
          echo TF_WORKSPACE=${{ matrix.workspace_environment }} >> $GITHUB_ENV
          echo TF_VAR_default_role=${{ matrix.role }} >> $GITHUB_ENV

      - name: Init & Plan
        run: |
          terraform init
          terraform plan --lock-timeout=300s --parallelism=200 --out=${{ env.TF_WORKSPACE }}.plan > ${{ env.TF_WORKSPACE }}.log

      - name: Output Plan
        run: |
          cat ${{ env.TF_WORKSPACE }}.log
          echo ''
          echo '----------------------Concise Plan---------------------------'
          cat ${{ env.TF_WORKSPACE }}.log | grep '\.' | grep '#' || true

      - name: Apply ${{ matrix.environment }}
        run:  terraform apply -parallelism=200 -lock-timeout=300s ${{ env.TF_WORKSPACE }}.plan
